"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _blogs_card from './blogs-card.bones.json'

registerBones({
  "blogs-card": _blogs_card,
})
